# Page settings

baseURL = "https://www.guyu.me/resume/"
languageCode = "en"
title = "顾宇的简历"
theme = "hugo-devresume-theme"
publishDir = "docs"
# googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "顾宇"
    description = "埃森哲（中国）有限公司通信、媒体和高科技事业部咨询经理"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "顾宇"
        tagline = "埃森哲（中国）有限公司通信、媒体和高科技事业部咨询经理"
        avatar = "avatar-square.png"







    [params.contact]
        enable = true
        location = "Shenzhen, China"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-globe"
        url = "#"
        text = "www.guyu.me"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript"
        [[params.skills.list.items]]
        details = "Python/Ruby/Go"
        [[params.skills.list.items]]
        details = "Node.js/Java"
        [[params.skills.list.items]]
        details = "Oracle/MySQL"
        [[params.skills.list.items]]
        details = "Git/Jenkins/AWS"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Consulting"
        [[params.skills.list.items]]
        details = "Facilitaion"
        [[params.skills.list.items]]
        details = "Coaching"
        [[params.skills.list.items]]
        details = "Presentation"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "软件工程 学士"
        university = "新疆大学软件学院"
        dates = "2005 - 2009"








    [params.awards]
        enable = true
        [[params.awards.list]]
        name = "年度案例"
        body = "TOP100 Case Study"
        date = "2019.11.16"


        [[params.awards.list]]
        name = "特邀讲师"
        body = "深圳敏捷之旅"
        date = "2019.09.22"


        [[params.awards.list]]
        name = "金牌讲师"
        body = "DevOps 国际峰会"
        date = "2019.07.05"







    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "中文"
        level = "母语"
        [[params.languages.list]]
        name = "英语"
        level = "商务会话"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "您好，我是顾宇，我目前专注于 DevOps，云计算，微服务和全功能敏捷团队的实践和推广。我在过去 6 年中在国内外不同规模的客户和项目中提供了敏捷，DevOps 和 微服务的培训、咨询和实施服务。并且参与了《研发运营一体化能力成熟度模型》（DevOps标准）和《分布式应用架构技术能力要求 第一部分：微服务平台》（微服务标准）的编写。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "技术咨询经理 - Tech Consulting Manager"
        dates = "2018.09 - Present"
        company = "Accenture"
        details = "担任咨询经理，为客户提供软件研发效率和应用架构方面的咨询。"
        [[params.experience.list.items]]
        details = "Agile: User Story/TDD/Scrum/Retrospective"
        [[params.experience.list.items]]
        details = "Architect: Domain-Driven-Design/MicroService/V-Model"

        [[params.experience.list]]
        title = "高级咨询师 - Senior Consultant"
        dates = "2013.09 - 2018.09"
        company = "ThoughtWorks"
        details = "担任软件工程师，架构师，以及 DevOps 咨询师。作为架构师，为各类客户的技术栈提供架构转型指导和实施，尤其是微服务架构，作为 DevOps 咨询师，帮助客户进行 DevOps 转型，并通过引入 DevOps 评估和技术工具提升客户的 DevOps 和自动化运维能力。作为软件工程师，采用敏捷的软件开发的方式进行编程，擅长 Java / Ruby / NodeJS  技术栈以及敏捷实践，如 XP，TDD 等。对 Python / Scala / R 语言有一些了解。"
        [[params.experience.list.items]]
        details = "Agile: User Story/TDD/Scrum/Retrospective"
        [[params.experience.list.items]]
        details = "Architect: MicroService"
        [[params.experience.list.items]]
        details = "Java: Gradle/Junit/Mockito/Grava/Spring/SpringBoot"
        [[params.experience.list.items]]
        details = "JavaScript: jQuery/NodeJS/AngularJS/Yoeman/Bower/Mocha/Chai/Karma"
        [[params.experience.list.items]]
        details = "Ruby: rake/gem/Bundle/Cucumber/Rails/Sinatra/Capybara"
        [[params.experience.list.items]]
        details = "Python: Pipenv/requests/pandas"
        [[params.experience.list.items]]
        details = "HTML/CSS"
        [[params.experience.list.items]]
        details = "MySQL"
        [[params.experience.list.items]]
        details = "AWS: Route53/S3/CloudFront/VPC/ELB/EC2/Lambda/CloudFormation/IAM/RDS"
        [[params.experience.list.items]]
        details = "DevOps: Git/Jenkins/Vagrant/Docker/Ansible"
        [[params.experience.list.items]]
        details = "SaaS: Trello/Sumologic/Splunk/NewRelic"
        
        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2010.08 - 2013.08"
        company = "亚信联创"
        details = "担任项目经理、维护经理、Java开发工程师。作为新疆移动10086 系统产品的维护负责人负责整个系统的维护，新建项目的开发，以及和 BOSS 系统以及其它外围系统的集成，需求沟通以及日常技术维护活动。主要采用 小型机，Oracle 数据库和 Oracle Weblogic Java 技术栈。"

        [[params.experience.list.items]]
        details = "Java"
        [[params.experience.list.items]]
        details = "JavaScript: jQuery"
        [[params.experience.list.items]]
        details = "HTML/CSS"
        [[params.experience.list.items]]
        details = "Oracle 10g"
        [[params.experience.list.items]]
        details = "Oracle Weblogic 8.1"

        [[params.experience.list]]
        title = "科员"
        dates = "2009.11 - 2010.08"
        company = "华夏银行乌鲁木齐分行 信息技术部"
        details = "维护华夏银行乌鲁木齐分行的业务系统。"

        [[params.experience.list]]
        title = "Java 开发工程师 - Backend Developer"
        dates = "2009.03 - 2009.11"
        company = "神州数码思特奇"
        details = "新疆联通 BSS 系统的割接，以及账务管理系统的维护。"
        [[params.experience.list.items]]
        details = "Java"
        [[params.experience.list.items]]
        details = "JavaScript: jQuery"
        [[params.experience.list.items]]
        details = "HTML/CSS"
        [[params.experience.list.items]]
        details = "Oracle 10g"
        [[params.experience.list.items]]
        details = "Oracle Weblogic 8.1"










    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Rokit"
        meta = "Open Source"
        tagline = "Rokit (Redirection Optimization Kit) is a CLI tool to help wed admin/developer to test or optimize URL redirection. It's easy to integrate into your CI as smoke test and regression test for redirection testing."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "对外分享 - 2019 年"
        [[params.information.list.items]]
        details = "2019.11.16 · 北京 · Top100Summit · 千人规模团队DevOps改进"
        [[params.information.list.items]]
        details = "2019.10.26 · 北京 · NCTS · DevOps的质量从需求质量开始"
        [[params.information.list.items]]
        details = "2019.09.22 · 深圳 · 敏捷之旅 · 2019.0922 · 深圳 · DevOps质量从用户故事开始"
        [[params.information.list.items]]
        details = "2019.07.06 · 北京 · DOIS · 微服务产品团队规模化DevOps演进模式"
        [[params.information.list.items]]
        details = "2019.06.23 · 深圳 · DevOpsMeetup · 千人规模DevOps组织演进模式"
        [[params.information.list.items]]
        details = "2019.05.23 · 香港 · CloudExpo · CloudNative DevOps"
        [[params.information.list]]
        title = "对外分享 - 2018 年"
        [[params.information.list.items]]
        details = "2018.11.17 · 上海 · CNUTCon · 一次微服务架构决策的案例"
        [[params.information.list.items]]
        details = "2018.11.03 · 深圳 · DOIS · 云原生下的 DevOps 新实践"
        [[params.information.list.items]]
        details = "2018.11.27 · 深圳 · 腾讯云 · 从DevOps标准评估中我们学到了什么"
        [[params.information.list.items]]
        details = "2018.10.14 · 厦门 · DevOpsMeetup · 一个敏捷开发团队的DevOps之路"
        [[params.information.list.items]]
        details = "2018.10.13 · 福州 · DevOpsMeetup · 一个敏捷开发团队的DevOps之路"
        [[params.information.list.items]]
        details = "2018.09.12 · 台北 · DevOpsDays · 用DevOps故事落地DevOps实践"
        [[params.information.list.items]]
        details = "2018.09.02 · 广州 · DevOpsMeetup · 用DevOps故事落地DevOps实践"
        [[params.information.list.items]]
        details = "2018.07.21 · 西安 · AgileTour · 团队敏捷文化构建工作坊"
        [[params.information.list.items]]
        details = "2018.06.30 · 北京 · DOIS · 成功的微服务应该是什么样"
        [[params.information.list.items]]
        details = "2018.06.29 · 北京 · DOIS · 应用设计标准解读"
        [[params.information.list.items]]
        details = "2018.06.02 · 深圳 · TechRadarSummit · CloudNativeDevOps"
        [[params.information.list.items]]
        details = "2018.04.15 · 深圳 · GOPS2018. · 微服务落地反思以及高效落地"
        [[params.information.list]]
        title = "对外分享 - 2017 年"
        [[params.information.list.items]]
        details = "2017.10.28 · 北京 · TechNeo · 用基础设施即代码自动化架构迁移"
        [[params.information.list.items]]
        details = "2017.10.21 · 厦门 · MDP · 微服务反思工作坊"
        [[params.information.list.items]]
        details = "2017.09.17 · 北京 · JAM · 大型团队Jenkins最佳实践分享"
        [[params.information.list.items]]
        details = "2017.08.18 · 上海 · DevOpsDays · 无服务器化的微服务持续交付"
        [[params.information.list.items]]
        details = "2017.07.29 · 北京 · QingCloudInsight · 当你的持续集成服务器成为安全隐患"
        [[params.information.list.items]]
        details = "2017.04.22 · 南京 · NJSD2017. · 打造你的DevOps技术雷达"
        [[params.information.list.items]]
        details = "2017.04.21 · 深圳 · GOPS2017. · DevOps可视化在电信企业的应用"
        [[params.information.list]]
        title = "对外分享 - 2016 年"
        [[params.information.list.items]]
        details = "2016.12.17 · 西安 · DevOpsMeetUp · MicroService In Serverless"
        [[params.information.list.items]]









    [params.social]
        enable = true

        [[params.social.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "//github.com/wizardbyron"
        title = "wizradbyron"
        [[params.social.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/wizradbyron"
        title = "wizradbyron"
        [[params.social.list]]
        style = "fab"
        icon = "fa-twitter-square"
        url = "//twitter.com/wizardbyron"
        title = "@wizradbyron"





