# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "顾宇"
    description = "埃森哲（中国）有限公司通信、媒体和高科技事业部咨询经理"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "顾宇"
        tagline = "埃森哲（中国）有限公司通信、媒体和高科技事业部咨询经理"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Shenzhen, China"

        [[params.contact.list]]
        style = "fas"
        icon = "fa-globe"
        url = "#"
        text = "www.guyu.me"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "软件工程 学士"
        university = "新疆大学软件学院"
        dates = "2005 - 2009"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "您好，我是顾宇，我目前专注于 DevOps，云计算，微服务和全功能敏捷团队的实践和推广。我在过去 6 年中在国内外不同规模的客户和项目中提供了敏捷，DevOps 和 微服务的培训、咨询和实施服务。并且参与了《研发运营一体化能力成熟度模型》（DevOps标准）和《分布式应用架构技术能力要求 第一部分：微服务平台》（微服务标准）的编写。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "对外分享 - 2019 年"
        [[params.information.list.items]]
        details = "2019.11.16 · 北京 · Top100Summit · 千人规模团队DevOps改进"
        [[params.information.list.items]]
        details = "2019.10.26 · 北京 · NCTS · DevOps的质量从需求质量开始"
        [[params.information.list.items]]
        details = "2019.09.22 · 深圳 · 敏捷之旅 · 2019.0922 · 深圳 · DevOps质量从用户故事开始"
        [[params.information.list.items]]
        details = "2019.07.06 · 北京 · DOIS · 微服务产品团队规模化DevOps演进模式"
        [[params.information.list.items]]
        details = "2019.06.23 · 深圳 · DevOpsMeetup · 千人规模DevOps组织演进模式"
        [[params.information.list.items]]
        details = "2019.05.23 · 香港 · CloudExpo · CloudNative DevOps"
        [[params.information.list]]
        title = "对外分享 - 2018 年"
        [[params.information.list.items]]
        details = "2018.11.17 · 上海 · CNUTCon · 一次微服务架构决策的案例"
        [[params.information.list.items]]
        details = "2018.11.03 · 深圳 · DOIS · 云原生下的 DevOps 新实践"
        [[params.information.list.items]]
        details = "2018.11.27 · 深圳 · 腾讯云 · 从DevOps标准评估中我们学到了什么"
        [[params.information.list.items]]
        details = "2018.10.14 · 厦门 · DevOpsMeetup · 一个敏捷开发团队的DevOps之路"
        [[params.information.list.items]]
        details = "2018.10.13 · 福州 · DevOpsMeetup · 一个敏捷开发团队的DevOps之路"
        [[params.information.list.items]]
        details = "2018.09.12 · 台北 · DevOpsDays · 用DevOps故事落地DevOps实践"
        [[params.information.list.items]]
        details = "2018.09.02 · 广州 · DevOpsMeetup · 用DevOps故事落地DevOps实践"
        [[params.information.list.items]]
        details = "2018.07.21 · 西安 · AgileTour · 团队敏捷文化构建工作坊"
        [[params.information.list.items]]
        details = "2018.06.30 · 北京 · DOIS · 成功的微服务应该是什么样"
        [[params.information.list.items]]
        details = "2018.06.29 · 北京 · DOIS · 应用设计标准解读"
        [[params.information.list.items]]
        details = "2018.06.02 · 深圳 · TechRadarSummit · CloudNativeDevOps"
        [[params.information.list.items]]
        details = "2018.04.15 · 深圳 · GOPS2018. · 微服务落地反思以及高效落地"
        [[params.information.list]]
        title = "对外分享 - 2017 年"
        [[params.information.list.items]]
        details = "2017.10.28 · 北京 · TechNeo · 用基础设施即代码自动化架构迁移"
        [[params.information.list.items]]
        details = "2017.10.21 · 厦门 · MDP · 微服务反思工作坊"
        [[params.information.list.items]]
        details = "2017.09.17 · 北京 · JAM · 大型团队Jenkins最佳实践分享"
        [[params.information.list.items]]
        details = "2017.08.18 · 上海 · DevOpsDays · 无服务器化的微服务持续交付"
        [[params.information.list.items]]
        details = "2017.07.29 · 北京 · QingCloudInsight · 当你的持续集成服务器成为安全隐患"
        [[params.information.list.items]]
        details = "2017.04.22 · 南京 · NJSD2017. · 打造你的DevOps技术雷达"
        [[params.information.list.items]]
        details = "2017.04.21 · 深圳 · GOPS2017. · DevOps可视化在电信企业的应用"
        [[params.information.list]]
        title = "对外分享 - 2016 年"
        [[params.information.list.items]]
        details = "2016.12.17 · 西安 · DevOpsMeetUp · MicroService In Serverless"
        [[params.information.list.items]]









    [params.social]
        enable = true

        [[params.social.list]]
        style = "fab"
        icon = "fa-github-square"
        url = "//github.com/wizardbyron"
        title = "wizradbyron"
        [[params.social.list]]
        style = "fab"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/wizradbyron"
        title = "wizradbyron"
        [[params.social.list]]
        style = "fab"
        icon = "fa-twitter-square"
        url = "//twitter.com/wizardbyron"
        title = "@wizradbyron"





